---
- name: Install MySQL and dependencies
  hosts: all
  become: true

  tasks:
    - name: Install aptitude package manager
      apt:
        name: aptitude
        state: present

    - name: Install MySQL and dependencies
      apt:
        name:
          - mysql-server
          - python3-mysqldb
          - libmysqlclient-dev
        state: present
        
---
---
- name: Install and configure MySQL
  hosts: all
  become: yes

  vars:
    mysql_root_password: "mysecretpassword" # change this to your desired root password

  tasks:
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Copy MySQL configuration file
      template:
        src: templates/mysql.cnf.j2
        dest: /etc/mysql/my.cnf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart MySQL

    - name: Create MySQL database
      mysql_db:
        name: mydb
        state: present
      become_user: mysql

    - name: Create MySQL user
      mysql_user:
        name: myuser
        password: mypassword
        priv: 'mydb.*:ALL'
        state: present
      become_user: mysql

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
