---
- hosts: mysql

  vars:
    mysql_root_password: Parasolka5

  tasks:
    - name: Instalacja mysql
      dnf:
        name: mysql-server
        state: present
    - name: Włącz Usługę
      service: name=mysqld state=started enabled=yes
    - name: Zaktualizuj dane konta
      no_log: true
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
    - name: Stwórz nową bazę
      mysql_db: name=matrix state=present login_user=root login_password="{{ mysql_root_password }}"
    - name: Skopiuj schemat
      copy: src=/usr/bazadanych/matrix.sql dest=/tmp/matrix.sql
    - name: Umieść przykładowe dane w bazie
      mysql_db: name=matrix state=import target=/tmp/matrix.sql login_user=root login_password="{{ mysql_root_password }}"
